# see: http://www.appveyor.com/docs/build-configuration#configuring-build


# configuration for deploy candidates (release / hotfix branches)
- 
  branches:
    only:
      - /release.*/
      - /hotfix.*/

  build_script:
     - cmd: msbuild /t:build /p:Configuration=Release /p:RunOctopack=false /p:OctoPackPublishPackageToHttp=http://youroctopusserverurl/nuget/packages /p:OctoPackPublishApiKey=API-key



# configuration for checking integration builds (develop branch; without OctoPack) 
- 
  branches:
    only:
      - /develop.*/

  build_script:
     - cmd: msbuild /t:build /p:Configuration=Release

