# see: http://www.appveyor.com/docs/build-configuration#configuring-build

version: 1.2.{build}
branches:
  only:
  - /release.*/
  - /hotfix.*/
configuration: Release

# scripts that are called at very beginning, before repo cloning
init:
- cmd: "set appVeyorBuildVersion=%appveyor_build_version%\necho appVeyorBuildVersion:%appVeyorBuildVersion% \n\necho repo branch:%APPVEYOR_REPO_BRANCH%\n\nset branch=%APPVEYOR_REPO_BRANCH%\necho branch:%branch%\n\nset gitVersion=%branch:~-3%\necho gitversion:%gitVersion%\n\nset version=%gitVersion%.%APPVEYOR_BUILD_NUMBER%\necho %version%\n\n"

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
build_script:
- cmd: "nuget restore\nmsbuild MyNugetServerSolution.sln /t:build /p:Configuration=Release /p:RunOctopack=true /p:OctoPackPublishPackageToHttp=http://devpccloud.cloudapp.net/nuget/packages /p:OctoPackPublishApiKey=API-9DUCGSPLW1AHA4LBQZSHWBS8BS"