# see: http://www.appveyor.com/docs/build-configuration#configuring-build

# Two configurations: For the develop branch,and for the release & hotfix branches
# The config for develop does not push the package for deployment, just checking that it builds.


# configuration for deploy candidates (release / hotfix branches)
- 
  branches:
    only:
      - /release.*/
      - /hotfix.*/

  configuration: Release

  # scripts that are called at very beginning, before repo cloning
  init:
  - ps: |
      function gitVersion(){
        write-host "This gets the version nr from the end of the git release branch (e.g.: v1.4). And updates the appVersion build nr with that."

        $branch=$env:APPVEYOR_REPO_BRANCH
    
        $posAfterVchar = $branch.LastIndexOf("v") + 1
        $versionLength = $branch.Length - $posAfterVchar
        
        $gitVersion=$branch.substring($posAfterVchar, $versionLength)
        
        $newVersion="$gitVersion.$env:APPVEYOR_BUILD_NUMBER"
        
        write-host "Update appveyor build version to:$newVersion"
        appveyor UpdateBuild -Version "$newVersion"
      }
      gitVersion
  

  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'

  build_script:
    - echo Building version:%appveyor_build_version%
    - cmd: msbuild /t:build /p:RunOctopack=false /p:OctoPackPublishPackageToHttp=http://youroctopusserverurl/nuget/packages /p:OctoPackPublishApiKey=API-key
  
  before_build:
    nuget restore


# configuration for checking integration builds (develop branch; without OctoPack) 
- 
  branches:
    only:
      - /develop.*/

  configuration: 
    - Debug
    - Release

  # no init section with git version

  assembly_info:
    patch: true
    file: '**\AssemblyInfo.*'
    assembly_version: '{version}'
    assembly_file_version: '{version}'
    assembly_informational_version: '{version}'

  build_script:
    - echo Building version:%appveyor_build_version%
    - cmd: msbuild /t:build 

  before_build:
    nuget restore
